# Generated by Django 3.1.7 on 2021-03-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='book',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.book'),
        ),
    ]
