# Generated by Django 3.1.7 on 2021-03-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210308_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.book', unique=True),
        ),
    ]
