# Generated by Django 3.1.7 on 2021-03-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210308_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.someuser'),
        ),
        migrations.DeleteModel(
            name='LikeToComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.grant'),
        ),
    ]
